export const IMPLEMENTED_GARPA_STAGES = [
  "claim_packet",
  "offering_admission",
  "mission_goal",
  "capability_graph",
  "component_substitution",
  "candidate_architecture",
  "qualification_contract",
  "build_manifest",
  "build_receipt",
  "preflight_receipt",
  "test_run_receipt",
  "custodied_mission_evaluation",
  "vendor_parity",
  "publication_gate",
  "release_verification",
  "counterevidence_review",
  "public_registry",
  "capability_commons_admission",
  "capability_commons_catalog",
  "commons_retrieval_plan",
  "commons_case_nomination",
  "commons_component_projection",
  "commons_seeded_substitution",
  "commons_seeded_architecture",
  "commons_seeded_qualification",
  "commons_seeded_build_manifest",
  "commons_seeded_build_receipt",
  "commons_seeded_preflight",
  "commons_seeded_test_run",
  "commons_seeded_mission_evaluation",
  "commons_seeded_vendor_parity",
  "commons_seeded_publication",
  "commons_seeded_release_verification",
] as const;

export type ImplementedGarpaStage = (typeof IMPLEMENTED_GARPA_STAGES)[number];
